// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6oh1bzWaWY_yAFne6wFdomEd1u-hWN8',
    appId: '1:479243495208:web:32d0eaf47a858f8b0a521d',
    messagingSenderId: '479243495208',
    projectId: 'quizclass-2da6c',
    authDomain: 'quizclass-2da6c.firebaseapp.com',
    storageBucket: 'quizclass-2da6c.firebasestorage.app',
    measurementId: 'G-ZZSPFNQBNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjK0pBMAkRZKZmGWTKgH-81PfdIOZ5yG8',
    appId: '1:479243495208:android:955e022e646b03270a521d',
    messagingSenderId: '479243495208',
    projectId: 'quizclass-2da6c',
    storageBucket: 'quizclass-2da6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fK7TEttWw34dCaN5zXPvnMaH31hTwDk',
    appId: '1:479243495208:ios:23d35387259225ff0a521d',
    messagingSenderId: '479243495208',
    projectId: 'quizclass-2da6c',
    storageBucket: 'quizclass-2da6c.firebasestorage.app',
    iosBundleId: 'com.example.educationProjectExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fK7TEttWw34dCaN5zXPvnMaH31hTwDk',
    appId: '1:479243495208:ios:23d35387259225ff0a521d',
    messagingSenderId: '479243495208',
    projectId: 'quizclass-2da6c',
    storageBucket: 'quizclass-2da6c.firebasestorage.app',
    iosBundleId: 'com.example.educationProjectExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh6oh1bzWaWY_yAFne6wFdomEd1u-hWN8',
    appId: '1:479243495208:web:5557cbc5e5013f350a521d',
    messagingSenderId: '479243495208',
    projectId: 'quizclass-2da6c',
    authDomain: 'quizclass-2da6c.firebaseapp.com',
    storageBucket: 'quizclass-2da6c.firebasestorage.app',
    measurementId: 'G-1ZDP5C5Q72',
  );
}
